### ISSUE TITLE
Hardware schematic update request

### ISSUE THREAD

**Issue by mrv96** [Grix/helios_dac#13]
Hi, looking Helios schematics i found some mismatchings between Kicad files and both Bill Of Materials and your PCB photos. For example, from BOM and photos i can see that your DC-DC converter provides +-12V, while the schematic include a +-9V DC-DC converter. Moreover DC-DC converter isolated ground (called 0V) is connected with the main GND, making the isolation useless. I think that schematic files are not updated to the last review, can you correct this incongruences please?

Thank you very much for your amazing work!

**Comment by Grix** [comment]
Hi,
I can take a look at this when I have time, it is very possible that the files are slightly outdated. But as for the DC-DC converter, it is fine with either 9V or 12V, and the ground does not need to be isolated, in fact it's probably better that it's not. Its only purpose is to provide the necessary voltages for the opamps. 
For the record, this is the BOM that was used for the most recent actual manufacturing batch: https://docs.google.com/spreadsheets/d/1PZRa1wW3mezbmuCuooRiO7qGqE42E1tUs300BoUyFXU/edit?usp=sharing

**Comment by mrv96** [comment]
Thank you very very much for the answer and for the updated BOM. I'll wait for Kikad project update. Thank you again for your work.

**Comment by Grix** [comment]
It should be up to date now. Except I didn't fix some labels like the 9V because as said it doesn't really matter, I think the only reason I used a +-12V instead was that the 9V converter was out of stock.
