### ISSUE TITLE
Enclosure type

### ISSUE THREAD

**Issue by hires** [Grix/helios_dac#16]
I'm interested in building a unit but only the PCB parts are shown in the BOM. Where is the enclosure part?

**Comment by Grix** [comment]
Hi,

This is the enclosure used: https://rfbat.com/collections/box-aluminum/products/new-aluminum-box-enclousure-case-project-electronic-diy-75-70-24l-w-h-black

However, the shelf variant of that enclose does not have the required connector cutouts, we have them custom made. This is probably prohibitively expensive for a one-off build if you don't have tools to cut out connector slots yourself, but we have some spare enclosures with the cutouts and engraving left over that you can order from here if you prefer: https://bitlasers.com/shop/helios-enclosure/
