### ISSUE TITLE
compiling shared library for macs

### ISSUE THREAD

**Issue by jdeboi** [Grix/helios_dac#20]
Admittedly I didn't totally know what I was doing, but when I compiled the shared library on my Mac, I got the error, " warning: ignoring file libusb-1.0.so, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format."

I resolved the issue by replacing libusb-1.0.so with libusb-1.0.0.dylib in the g++ command. This might be an obvious substitution, but I struggled to figure this out for a while. Might be helpful to others to include a hint in the readme.  thanks!

**Comment by Grix** [comment]
Thanks, I will make a note of it in the readme.
