### ISSUE TITLE
Having issues linking against x64 .lib file 

### ISSUE THREAD

**Issue by DNCrosby** [Grix/helios_dac#24]
When I compile I get the following error and I didn't see a libusb-1.0_x64.lib

Source\ThirdParty\HeliosDacLibrary\x64\Release\libusb-1.0.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'

**Comment by Grix** [comment]
> and I didn't see a libusb-1.0_x64.lib

https://github.com/Grix/helios_dac/blob/master/sdk/libusb-1.0-x64.dll

**Comment by Grix** [comment]
You can download libusb binaries from here, there should be both .lib and .dll versions for all OSes: https://sourceforge.net/projects/libusb/files/libusb-1.0/libusb-1.0.26/
