### ISSUE TITLE
Disconnect ILDA ground when inactive

### ISSUE THREAD

**Issue by PatHightree** [Grix/helios_dac#25]
Would it be possible to disconnect the ground of the ILDA connection until actual data is transmitted ?
I'm using a Laserworld DS1000 which has 2 inputs ILDA and ethernet.
I'd like to have keep cables connected but the ethernet input is disabled as soon as the ILDA cable is connected to the DAC.
This is by design, the manufacturer [advises](https://showcontroller.com/en/forum/hardware-and-installation/154-connect-ds1000-via-both-ethernet-and-ilda.html#473) me to disconnect the ILDA cable at the DAC to use ethernet.
But he mentions that disconnecting the ILDA ground signal would also do the trick.
So I'm wondering if that could be done by the Helios DAC.

**Comment by Grix** [comment]
Unfortunately this isn't possible on the official device, the ground signals in the ILDA cable are hardwired.

**Comment by PatHightree** [comment]
Yeah I figured as much, thanks for confirming.
