### ISSUE TITLE
Linux python example issues

### ISSUE THREAD

**Issue by maltefuchs** [Grix/helios_dac#8]
Hey

I recently purchased a Helios DAC and I`m having problems using the python example for linux. 

I used an oszilloscope to display the output of the DAC and to eliminate any influence of other hardware. If If run LaserShowGen on OS X everything seems to work fine. The DAC is recognised and frames are shown just fine (even though somehow distorted on the oszilloscope). 

However if I try to run the python example file on Ubuntu (also on a macbook) the DAC is recognized and loads the first frame but gets stuck afterwards. I tried to analyze the problem further and found that after loading the first frame HeliosLib.GetStatus(j) keeps returning 0, so it`s never ready to receive another frame.

I tried using a frame with fewer points (down to 1) but nothing changed. I also tried changing the flags of "int WriteFrame" in all sorts of combinations but wasn`t lucky either.

Has anyone observerd something similar or has any ideas how to solve the issue?

Thanks a lot for any help!

Kind regards
Malte

**Comment by Grix** [comment]
Hi,
I checked and it seems the library .so file in the python example folder was outdated. I recompiled from the source and updated the file in the folder, and it fixed the problem for me. So now it should work as-is. Try again and let me know.

**Comment by maltefuchs** [comment]
Hey,

thanks a lot for the quick fix. I will test it as soon as I can and let you how it went.

Kind regards
Malte

**Comment by maltefuchs** [comment]
Hi,
I just tried it again with the updated file and it works fine now. Thank you for fixing it!

Kind regards
 Malte

**Comment by Grix** [comment]
Good to hear
